### PR TITLE
fix(configs): Create non-existent parent directories automatically

### LINKED ISSUE #232: Can't mount Compose config at a path that doesn't exist in container
The deployment of the following compose file:
```yaml
services:
  grafana:
    image: grafana/grafana:12.2.0
    configs:
      - source: grafana-dashboard-victoriametrics
        target: /var/lib/grafana/dashboards/victoriametrics.json
    volumes:
      - grafanadata:/var/lib/grafana

configs:
  grafana-dashboard-victoriametrics:
    file: ./grafana/dashboards/victoriametrics.json

volumes:
  grafanadata:
```
fails with the following error:
```
Error: deploy services: create container: rpc error: code = Internal desc = inject configs: copy config file 'grafana-dashboard-victoriametrics' to container: copy to container: Error response from daemon: Could not find the file /var/lib/grafana/dashboards in container a9a6b7eeda4dbd8a6ea1f43bb66b2cba085d7c0fa2c9a71fb21f4d86a3a917b7
```

`/var/lib/grafana/dashboards/` directory doesn't exist in the container when we mount a new empty volume at `/var/lib/grafana`. However, `docker compose up` successfully runs the following compose file and mounts the config as expected.

We need to compare the implementation details of copying configs to created containers in uncloud and docker compose and make it work in uncloud in a similar way.
I don't know the details off the top of my head, but I suspect that we might want the `target` for the docker `CopyToContainer` call to always be the root `"/"`. And then create the full file paths that start from the container root in the tar archive. This way unarchiving such a tar will result in creating all intermediate directories that weren't originally present.

cc @tonyo

### PR DESCRIPTION
**Pull request by tonyo**
Fixes #232 and another issue that didn't allow to create two config mounts with the same source config.

It should more closely mirror now the Compose behavior which also uses the full target path in the tar header and extracts it to the root:

* https://github.com/docker/compose/blob/59f04b85af552dab7561255dcc08e9328c5bfe67/pkg/compose/secrets.go#L131
* https://github.com/docker/compose/blob/59f04b85af552dab7561255dcc08e9328c5bfe67/pkg/compose/secrets.go#L162

### CODE REVIEW

File: pkg/client/compose/config.go [hunk 1]
```diff
@@ -71,5 +78,11 @@ func configSpecsFromCompose(
 		configMounts = append(configMounts, mount)
```
Comment (psviderski) [inline pkg/client/compose/config.go:78]: Just found out that `ContainerSpec.Equal` depends on the order of config mounts. This is not a big deal as usually people update and deploy the same Compose file so the order of `service.configs` normally stays the same hence the spec comparison works as expected.

However, while we're on this, it would be good to make the comparison order agnostic, like with volume mounts to not trigger a spec change/redeployment if only the order is different: https://github.com/psviderski/uncloud/blob/79dc05cb665d6541ea2ff1ca16af4119ae6b47d4/pkg/api/service.go#L289-L300

**Review by psviderski — APPROVED** [review]
Excellent! Just one note about the `Equal` implementation for the config mounts. We can do it in a separate PR. It's up to you to decide, just raising to not forget.

File: pkg/client/compose/config.go (hunk 1 above)
Comment (tonyo) [reply pkg/client/compose/config.go:78]: Makes sense, but will handle it in another PR
